apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-api
  template:
    metadata:
      labels:
        app: content-api
    spec:
      containers:
        - name: content-api
          image: shinekumar23/content-api:1.3
      imagePullSecrets:
        - name: content-api-secret
          env:
            - name: NODE_ENV
              value: production
          ports:
            - containerPort: 3000
