name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      id: build
    - name: Build the Docker image
      run: |
        current_version=$(cat versions.txt 2>/dev/null)
        if [[ -z "$current_version" ]]; then
          # Set initial version as 1.0 if versions.txt is empty
          new_version=1.0
          echo "${{ secrets.DOCKERGITPW }}" | docker login ghcr.io --username shinekumar23 --password-stdin
          docker image build -t ghcr.io/shinekumar23/content-api:$new_version .
          docker push ghcr.io/shinekumar23/content-api:$new_version
          echo $new_version >> versions.txt
          sed -i "s|image: shinekumar23/content-api:1.0|image: shinekumar23/content-api:$new_version|" deployment/deployment.yaml
          git config --local user.email "shinekumar23@gmail.com"
          git config --local user.name "shinekumar23" 
          git commit -a -m "Updated version tag"
          git push origin main
        else
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version
          current_version=$(tail -1 versions.txt)
          echo $current_version
          increment=0.1
          new_version=$(echo "$current_version + $increment" | bc)
          echo "${{ secrets.DOCKERGITPW }}" | docker login ghcr.io --username shinekumar23 --password-stdin
          docker image build -t ghcr.io/shinekumar23/content-api:$new_version .
          docker push ghcr.io/shinekumar23/content-api:$new_version
          echo $new_version >> versions.txt
          sed -i "s|image: shinekumar23/content-api:1.0|image: shinekumar23/content-api:$new_version|" deployment/deployment.yaml
          git config --local user.email "shinekumar23@gmail.com"
          git config --local user.name "shinekumar23" 
          git commit -a -m "Updated version tag"
          git push origin main
        fi
