name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      id: build
    - name: Build the Docker image
      run: |
        current_version=$(cat versions.txt 2>/dev/null)
        if [[ -z "$current_version" ]]; then
          # Set initial version as 1.0 if versions.txt is empty
          new_version=1.0
          echo $new_version >> versions.txt
          cat versions.txt
          git config --local user.email "shinekumar23@gmail.com"
          git config --local user.name "shinekumar23" 
          git commit -a -m "Updated version tag"
          git push origin main
        else
          current_version=$(tail -1 versions.txt)
          echo $current_version
          increment=0.1
          new_version=$(echo "$current_version + $increment" | bc)
          echo $new_version >> versions.txt
          cat versions.txt
          git config --local user.email "shinekumar23@gmail.com"
          git config --local user.name "shinekumar23" 
          git commit -a -m "Updated version tag"
          git push origin main
        fi
        
        echo "${{ secrets.DOCKERPW }}" | docker login -u "shinekumar23" --password-stdin
        docker image build -t shinekumar23/content-api:$new_version .
        docker push shinekumar23/content-api:$new_version
      
