name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        current_version=$(cat versions.txt 2>/dev/null)
        if [[ -z "$current_version" ]]; then
          # Set initial version as 1.0 if versions.txt is empty
          current_version="1.0"
          echo "$current_version" >> versions.txt
        else
          current_version=$(tail -1 versions.txt)
        fi
        cat versions.txt

        echo "${{ secrets.DOCKERPW }}" | docker login -u "shinekumar23" --password-stdin
        docker image build -t shinekumar23/content-api:$current_version .
        docker push shinekumar23/content-api:$current_version
        
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Create local changes
      run: |
        # Generate the new version
        current_version=$(tail -1 versions.txt)
        new_version=$current_version+0.1
        echo "$new_version" >> versions.txt
        cat versions.txt

    - name: Commit files
      run: |
        git config --local user.email "shinekumar23@gmail.com"
        git config --local user.name "shinekumar23"
        git commit -a -m "Updated version tag"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
